### PR TITLE
lightning/restore: fix #812, ensure engines are restored in fixed order

### LINKED ISSUE #812: Lightning Disk Quota is not fully respected after restart due to non-deterministic engine selection
Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

1. Prepare a 1 TB data dump, 
2. Set batch size to 100 GB (so it is split into ~10 batches),
3. Set disk quota to 200 GB,
4. Set engine-concurrency to 6,
5. Run Lightning,
6. After 50 minutes (i.e. after the first disk-quota import has triggered), kill -9 Lightning.
7. Run Lightning again,

### 2. What did you expect to see?

Import continues with no errors.

### 3. What did you see instead?

After 20 minutes, Lightning crashed with "no space left on device" error.

```
[2021/03/05 09:24:42.639 +00:00] [ERROR] [restore.go:315] ["the whole procedure failed"] [takeTime=22m59.878871993s] [error="restore table `dq`.`g` failed: write /data1/data/lightning/kv/9ebefdf0-dc5c-4e88-b15a-0169065dcdaa.sst: no space left on device"]
```

### 4. What version of BR and TiDB/TiKV/PD are you using?

Lightning: nightly = f1daf8a4d6d14dcd2ce52766ae9428c435d33616,
Cluster: v4.0.11

### Misc 

This bug happens because the list of engines opened by the first and second invocation are different. So even if the disk usage from the currently active engine did not exceed 200 GB, the actual total counting the previous run already exceeds it.

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

Fix #812

### What is changed and how it works?

(Split off from #815). 

#812 is caused by iterating `cp.Engines` in `restoreEngines()`, which is a hash map. We read the map into a sorted array and iterate that instead, so engines are always restored in deterministic order.

### Check List 

Tests 

 - Integration test
 - Manual test
     * Import a 1 TB table with checkpoint
     * Kill Lightning
     * Restart Lightning
     * Note that the same engines (0, 1, 2, ...) are used in both steps 1 and 3, instead of randomly chosen ones.

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch
    * release-4.0

### Release Note

 - When resuming from checkpoint, Lightning now keeps restoring the original engines instead of starting to process some random new ones (#815).

### CODE REVIEW

File: tests/lightning_checkpoint_engines/run.sh [hunk 1]
```diff
@@ -81,13 +81,17 @@ for BACKEND in importer local; do
...
-  set +e
   for i in $(seq "$ENGINE_COUNT"); do
       echo "******** Importing Table Now (step $i/$ENGINE_COUNT) ********"
+      set +e
       do_run_lightning $BACKEND mysql 2> /dev/null
       [ $? -ne 0 ] || exit 1
+      set -e
+      # make sure the data engines are processed in the engine_id order.
+      # there is 75% this test failing if they are processed randomly.
+      run_sql 'SELECT *, status <= prev_engine_status AS ordering FROM (SELECT table_name, engine_id, status, lag(status) OVER (PARTITION BY table_name ORDER BY engine_id) AS prev_engine_status FROM tidb_lightning_checkpoint.engine_v5 WHERE engine_id >= 0) _'
```
Comment (glorv) [inline tests/lightning_checkpoint_engines/run.sh:92]: So I think this check should be `status < prev_engine_status` or add another restriction that `status >= 120`

Comment (kennytm) [reply tests/lightning_checkpoint_engines/run.sh]: changed to a more dedicated test case.

**Review by glorv — COMMENTED** [review]
rest LGTM

**Review by glorv — COMMENTED** [review]
/lgtm

**Review by ti-srebot — APPROVED** [review]
