### PR TITLE
*: strip PD urls with http or https

### LINKED ISSUE #536: `--pd` parameter does not allow prefix http(s)://
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
With current br, if we run `br backup full --pd http://10.200.45.133:2374 ...`, the error log will much like:
```
[2020/09/18 15:23:38.348 +08:00] [INFO] [common.go:381] [arguments] [log-file=/ssd/br/backup20200918/backupfull.log] [pd="[http://10.200.45.133:2374]"] [ratelimit=120] [storage=local:///ssd/br/backup20200918]
[2020/09/18 15:23:38.348 +08:00] [INFO] [client.go:148] ["[pd] create pd client with endpoints"] [pd-address="[http:]"]
[2020/09/18 15:23:38.501 +08:00] [WARN] [base_client.go:181] ["[pd] failed to get cluster id"] [url=http://http:] [error="[PD:client:ErrClientGetMember]error:rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: lookup http on 127.0.0.1:53: no such host\" target:http: status:TRANSIENT_FAILURE"]
```

The root cause is that we should use `10.200.45.133:2374` instead of `http://10.200.45.133:2374`, but the error log is quite confusing. Br should either provide more user friendly error log or be compatible with pd address start `with http(s)://`

2. What did you expect to see?

3. What did you see instead?

4. What version of BR and TiDB/TiKV/PD are you using?

### PR DESCRIPTION
**Pull request by YuJuncen**
Signed-off-by: Hillium <maruruku@stu.csust.edu.cn>

### What problem does this PR solve? 
fix #536 

### What is changed and how it works?
We check PD URLs and strip prefix before running.

### Check List 

Tests 

 - Unit test
 - Integration test

### Release Note

 - Fix a bug that caused failure when using `--pd` with urls starts with `http` or `https`.

### CODE REVIEW

File: pkg/task/common.go [hunk 1]
```diff
@@ -436,3 +450,17 @@ func (cfg *Config) adjust() {
...
+	startsWithHTTPS := strings.HasPrefix(pd, "https://")
+	if useTLS && startsWithHTTP {
+		return "", errors.Annotate(berrors.ErrInvalidArgument, "pd url starts with http while TLS enabled")
+	}
+	if !useTLS && startsWithHTTPS {
+		return "", errors.Annotate(berrors.ErrInvalidArgument, "pd url starts with https while TLS disabled")
+	}
+
+	striped := strings.TrimPrefix(strings.TrimPrefix(pd, "https://"), "http://")
+	return striped, nil
```
Comment (kennytm) [inline pkg/task/common.go:465]:
```go
if strings.HasPrefix(pd, "http://") {
    if useTLS {
        return "", errors.Annotate(...)
    }
    return strings.TrimPrefix(pd, "http://"), nil
} 
if strings.HasPrefix(pd, "https://") {
    if !useTLS {
        ...
    }
    ...
} 
return pd, nil
```

**Review by kennytm — COMMENTED** [review]
Rest LGTM. 

Also, fix the integration test.

**Review by kennytm — COMMENTED** [review]
Lgtm

File: pkg/restore/split_client.go [hunk 2]
```diff
@@ -247,7 +247,7 @@ func (c *pdClient) sendSplitRegionRequest(
 		} else {
 			if len(regionInfo.Region.Peers) == 0 {
 				return nil, multierr.Append(splitErrors,
-					errors.Errorf("region[%d] doesn't have any peer", regionInfo.Region.GetId()))
+					errors.Annotatef(berrors.ErrKVUnknown, "region[%d] doesn't have any peer", regionInfo.Region.GetId()))
```
Comment (3pointer) [inline pkg/restore/split_client.go:250]: berrors.ErrRestoreNoPeer

Comment (YuJuncen) [reply pkg/restore/split_client.go:250]: How about blocking it until #533 merged? So we can leave it untouched.

**Review by 3pointer — APPROVED** [review]
LGTM

**Review by ti-srebot — APPROVED** [review]
