### PR TITLE
pkg/lightning: check compatibility with  tiflash

### LINKED ISSUE #965: Lightning load data into table with tiflash replica failed
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Use lightning v4.0.11 to load data into tidb v4.0.0 with tiflash failed.
```
[2021/03/29 07:48:00.004 +00:00] [ERROR] [main.go:91] ["tidb lightning encountered error stack info"] [error="restore table `tpcc`.`orders` failed: EOF"] [errorVerbose="EOF\ngithub.com/pingcap/errors.AddStack\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/juju_adaptor.go:15\ngithub.com/pingcap/tidb-lightning/lightning/restore.(*TableRestore).importKV\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb-lightning/lightning/restore/restore.go:2044\ngithub.com/pingcap/tidb-lightning/lightning/restore.(*TableRestore).importEngine\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb-lightning/lightning/restore/restore.go:1521\ngithub.com/pingcap/tidb-lightning/lightning/restore.(*TableRestore).restoreEngines.func1\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb-lightning/lightning/restore/restore.go:1301\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\nrestore table `tpcc`.`orders` failed"]
[2021/03/29 07:48:00.004 +00:00] [ERROR] [main.go:92] ["tidb lightning encountered error"] [error="restore table `tpcc`.`orders` failed: EOF"]
```

4. What version of BR and TiDB/TiKV/PD are you using?

Lightning : v4.0.11

TiDB: v4.0.0

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
Return error at check-requirement if tidb cluster <= "v4.0.4" and some table contains tiflash replicas.

close #965

### Check List 

Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### Release Note

 - Make return error more user-friendly when lightning load data into tables with TiFlash replica but cluster version is too old.

### CODE REVIEW

File: pkg/lightning/restore/restore.go [hunk 1]
```diff
@@ -1879,12 +1887,68 @@ func (rc *RestoreController) enforceDiskQuota(ctx context.Context) {
...
 	if !rc.cfg.App.CheckRequirements {
 		return nil
 	}
-	return rc.backend.CheckRequirements(ctx)
+	if err := rc.backend.CheckRequirements(ctx); err != nil {
+		return errors.Trace(err)
+	}
+	// check TiFlash replicas.
+	// local backend doesn't support TiFlash before tidb v4.0.5
+	if rc.cfg.TikvImporter.Backend == config.BackendLocal {
```
[the remark this answers is not in the document]
Comment (glorv) [reply pkg/lightning/restore/restore.go:1905]: shall we put `MDDatabaseMeta ` into context to avoid the extra function parameter which is only used in local backend🤔

File: pkg/lightning/backend/local/local.go [hunk 2]
```diff
@@ -1465,20 +1474,49 @@ func (local *local) CheckRequirements(ctx context.Context) error {
...
+
+	for _, dbMeta := range checkCtx.DBMetas {
+		for _, tblMeta := range dbMeta.Tables {
+			if len(tblMeta.DataFiles) == 0 {
+				continue
+			}
+			name := common.UniqueTable(dbMeta.Name, tblMeta.Name)
+			if _, ok := tiflashTables[name]; ok {
+				helpInfo := "Please either upgrade TiDB to version >= 4.0.5 or add TiFlash replica after load data."
+				return errors.Errorf("lightning local backend doesn't support TiFlash in this TiDB version. conflict table: %s. "+helpInfo, name)
```
Comment (kennytm) [inline pkg/lightning/backend/local/local.go:1515]: let's collect all table names and move this error after the loop.

File: pkg/lightning/backend/local/local.go [hunk 3]
```diff
@@ -1465,20 +1474,49 @@ func (local *local) CheckRequirements(ctx context.Context) error {
...
-		return errors.Trace(err)
+		return errors.Annotate(err, "fetch tiflash replica info failed")
 	}
 
-	return version.CheckTiDBVersion(versionStr, requiredMinVersion, requiredMaxVersion)
+	tiflashTables := make(map[string]struct{}, len(res))
+	for _, tblInfo := range res {
+		name := common.UniqueTable(tblInfo[0], tblInfo[1])
+		tiflashTables[name] = struct{}{}
+	}
```
Comment (kennytm) [inline pkg/lightning/backend/local/local.go:1505]: use `type namePair struct { db string; table string }` as the key.

**Review by kennytm — COMMENTED** [review]
rest LGTM

File: pkg/lightning/restore/restore.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (kennytm) [reply pkg/lightning/restore/restore.go]: that's ok.

File: pkg/lightning/backend/local/local_test.go [hunk 4]
```diff
@@ -480,3 +484,52 @@ func (s *localSuite) TestIsIngestRetryable(c *C) {
...
+		},
+	}
+	checkCtx := &backend.CheckCtx{DBMetas: dbMetas}
+
+	glue.EXPECT().GetSQLExecutor().Return(exec)
+	exec.EXPECT().QueryStringsWithLog(ctx, tiFlashReplicaQuery, gomock.Any(), gomock.Any()).
+		Return([][]string{{"db", "tbl"}, {"test", "t1"}, {"test1", "tbl"}}, nil)
+
+	err := checkTiFlashVersion(ctx, glue, checkCtx, *semver.New("4.0.2"))
+	c.Assert(err, ErrorMatches, "lightning local backend doesn't support TiFlash in this TiDB version. conflict tables: \\[`test`.`t1`, `test1`.`tbl`\\].*")
```
Comment (kennytm) [inline pkg/lightning/backend/local/local_test.go:534]:
```suggestion
	c.Assert(err, ErrorMatches, "lightning local backend doesn't support TiFlash in this TiDB version. conflict tables: \\[`test`\\.`t1`, `test1`\\.`tbl`\\].*")
```
