### PR TITLE
glue: set query DDL when executing DDLs

### LINKED ISSUE #364: DDL through CreateDatabase or CreateTable gets wrong query
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

We need to set the query for the DDL, [like this](https://github.com/pingcap/tidb/blob/7daa4a7f88194a9d4317a27acdf2143312375cd5/session/session.go#L1187)

```go
se.SetValue(sessionctx.QueryString, s.OriginText())
```

But we didn't set it, so query in DDL history is wrong.

4. What version of BR and TiDB/TiKV/PD are you using?

### PR DESCRIPTION
**Pull request by YuJuncen**
### What problem does this PR solve? 
fix #364 

### What is changed and how it works?
Before executing DDLs, we call `session.SetVar` firstly, inject the DDL by `SHOW CREATE TABLE`.

### Check List 

Tests 

 - Integration test

### Release Note

 - No release note

### CODE REVIEW

File: pkg/gluetidb/glue.go [hunk 1]
```diff
@@ -79,19 +105,63 @@ func (gs *tidbSession) CreateDatabase(ctx context.Context, schema *model.DBInfo)
...
+	table := tbl.Clone()
+	table.AutoIncID = 0
+	result := bytes.NewBuffer(make([]byte, 0, defaultCapOfCreateTable))
+	alloc, err := gs.allocatorFor(tbl, dbName)
+	if err != nil {
+		return "", err
+	}
+	// this can never fail.
+	_, _ = result.WriteString(brComment)
+	if err := executor.ConstructResultOfShowCreateTable(gs.se, tbl, alloc, result); err != nil {
```
Comment (kennytm) [inline pkg/gluetidb/glue.go:152]: let's just pass `nil` here. the allocators are only used for reading out the auto-inc and auto-random IDs which we will explicitly reset anyway.

```suggestion
	if err := executor.ConstructResultOfShowCreateTable(gs.se, tbl, nil, result); err != nil {
```

Comment (YuJuncen) [reply pkg/gluetidb/glue.go:152]: I do want to do that, but when this is `nil`, we will meet a panic if the table has auto increment columns...

Comment (YuJuncen) [reply pkg/gluetidb/glue.go:152]: (at executor/show.go:907)

Comment (kennytm) [reply pkg/gluetidb/glue.go:152]: @YuJencen what about `autoid.Allocators{}`

Comment (YuJuncen) [reply pkg/gluetidb/glue.go:152]: `autoid.Allocators` doesn't implement `Allocator`. 😢

Comment (kennytm) [reply pkg/gluetidb/glue.go:152]: Oops it was just [changed to `Allocators`](https://github.com/pingcap/tidb/blob/a99fdc098cb3bccc63ca74dad3d682b6f80a0fbd/executor/show.go#L722) in the latest master since pingcap/tidb#18217 👀

Comment (YuJuncen) [reply pkg/gluetidb/glue.go:152]: OK, seems after we update tidb to newest master, we can give it a `autoid.Allcators{}`. 😄

**Comment by YuJuncen** [comment]
Let's block it until the update TiDB version PR merged before the version frozen.

File: tests/br_db/run.sh [hunk 2]
```diff
@@ -51,4 +51,9 @@ if [ "$table_count" -ne "2" ];then
     exit 1
 fi
 
+# Test BR DDL query string
+echo "testing DDL query..."
+curl 127.0.0.1:10080/ddl/history | grep -E '/\*from(.*)\*/CREATE TABLE'
+curl 127.0.0.1:10080/ddl/history | grep -E '/\*from(.*)\*/CREATE DATABASE'
```
Comment (kennytm) [inline tests/br_db/run.sh:57]:
```suggestion
curl 127.0.0.1:10080/ddl/history | grep -E '/\*from('"'br'"')\*/CREATE TABLE'
curl 127.0.0.1:10080/ddl/history | grep -E '/\*from('"'br'"')\*/CREATE DATABASE'
```

**Comment by YuJuncen** [comment]
`java.net.ProtocolException: Expected HTTP 101 response but was '500 Internal Server Error'`

/run-integration-test
