### PR TITLE
tests: extend minio wait time to stable minio slow start

### LINKED ISSUE #799: Test lightning_s3 fails
1. What did you do?
If possible, provide a recipe for reproducing the error.

The test fails due to fail to start minio server.

```
[2021-03-04T06:37:43.896Z] + bin/minio server --address 127.0.0.1:9900 /tmp/backup_restore_test/s3.mydump
[2021-03-04T06:37:43.896Z] * About to connect() to 127.0.0.1 port 9900 (#0)
[2021-03-04T06:37:43.896Z] *   Trying 127.0.0.1...
[2021-03-04T06:37:43.896Z] * Connection refused
...
```

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/5315/pipeline#step-1308-log-47

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve? 

Minio server may be slow to start, so extend wait time to stable tests.

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/5239/pipeline/#step-1448-log-88

The test above shows starting a minio server may require 14 seconds or more.

Close #799 

### Check List 

Tests 

 - Integration test

Related changes

 - Need to cherry-pick to the release branch

### Release Note

 - No release note

### CODE REVIEW

File: tests/lightning_s3/run.sh [hunk 1]
```diff
@@ -32,22 +32,16 @@ export S3_ENDPOINT=127.0.0.1:9900
...
         echo 'Failed to start minio'
         exit 1
     fi
     sleep 2
 done
 
-stop_minio() {
-    kill -2 $MINIO_PID
-}
-trap stop_minio EXIT
```
Comment (kennytm) [inline tests/lightning_s3/run.sh:49]: why not kill it?

Comment (overvenus) [reply tests/lightning_s3/run.sh:49]: minio is killed in `stop_services`.

**Review by ti-srebot — APPROVED** [review]
