### PR TITLE
tests: make unblocksChecker get time synchronously

### LINKED ISSUE #778: Test pauseSuite.TestPause fails
1. What did you do?
If possible, provide a recipe for reproducing the error.

```
[2021-03-02T11:32:19.313Z] FAIL: pause_test.go:62: pauseSuite.TestPause
[2021-03-02T11:32:19.313Z] 
[2021-03-02T11:32:19.313Z] pause_test.go:99:
[2021-03-02T11:32:19.313Z]     c.Assert(&wg, unblocksBetween, 500*time.Millisecond, 520*time.Millisecond)
[2021-03-02T11:32:19.313Z] ... waitGroupPtr *sync.WaitGroup = &sync.WaitGroup{noCopy:sync.noCopy{}, state1:[3]uint32{0x0, 0x0, 0x0}}
[2021-03-02T11:32:19.313Z] ... min time.Duration = 500000000 ("500ms")
[2021-03-02T11:32:19.313Z] ... max time.Duration = 520000000 ("520ms")
[2021-03-02T11:32:19.313Z] ... WaitGroup did not unblock after maximum duration
```

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/5062/pipeline/69#step-360-log-118

### PR DESCRIPTION
**Pull request by YuJuncen**
### What problem does this PR solve? 
Fixed #778.

### What is changed and how it works?
See [here](https://github.com/pingcap/br/issues/778#issuecomment-789585338).

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

<details>
<summary>With this script:</summary>

```bash
#!/bin/bash
i=0
success=0
while ((i<10)); do
if ! go test -count=1 github.com/pingcap/br/pkg/lightning/common 2>&1 >test_result.txt; then
        cp test_result.txt test_result_failed$i.txt
        ((i++))
else
        ((success++))
        if (( success % 50 == 1)); then
                echo -e "\rsuccess $success times..."
        fi
        if (( success > 1000000 )); then
                break
        fi
fi
done
```
</details>

Have succeed at least  18151 times... Without any failure.

### Release Note

 - No release note.

### CODE REVIEW

File: pkg/lightning/common/pause_test.go [hunk 1]
```diff
@@ -39,19 +39,24 @@ func (checker *unblocksChecker) Check(params []interface{}, names []string) (boo
...
-			return false, "WaitGroup unblocked before minimum duration"
+			return false, "WaitGroup unblocked before minimum duration, it was " + dur.String()
 		}
 		return true, ""
 	case <-time.After(max):
-		return false, "WaitGroup did not unblock after maximum duration"
+		select {
+		case dur := <-ch:
+			return false, "WaitGroup did not unblock after maximum duration, it was " + dur.String()
+		case <-time.After(1 * time.Second):
```
Comment (3pointer) [inline pkg/lightning/common/pause_test.go:57]: why wait one more second?

Comment (YuJuncen) [reply pkg/lightning/common/pause_test.go:57]: If we meet `WaitGroup did not unblock after maximum duration` again, we can get the real time it takes to unblock. This might would be useful to find the failure was caused by meaning test requirement or some thing worse(like, deadlock).

**Review by 3pointer — COMMENTED** [review]
/lgtm

**Review by ti-srebot — APPROVED** [review]
