### PR TITLE
*: when cleaning up, use isolated context

### LINKED ISSUE #557: BR won't clean up the environment when exit by SIGTERM
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
- start BR (restore or backcup with `--remove-schedulers`)
- waiting for the progress bar present, then press <kbd>ctrl</kbd> + <kbd>c</kbd>

2. What did you expect to see?
The cluster config changed by BR should be undone, since SIGTERM allows us to gracefully stop.

3. What did you see instead?
The cluster has stuck in the config that BR has set. (For current master, PD schedulers could be reset due to #551 )
image

4. What version of BR and TiDB/TiKV/PD are you using?

v4.0.7

#### Note:

We listen to signals here:

https://github.com/pingcap/br/blob/d2d5bbaf29bdbc2b1d9453ec65096e04c52b529e/main.go#L34-L39

Canceling the context could make other goroutines eventually exit and clean up, but we leave no time for them.

<del>Add a `time.Sleep(30 * time.Second)`</del> remove those `os.Exit`s could help. But there are still some problems:

https://github.com/pingcap/br/blob/d2d5bbaf29bdbc2b1d9453ec65096e04c52b529e/pkg/task/backup.go#L222-L227

We use the global context to do the cleanup tasks, which will always fail if the outer context is canceled. We should change it to a new context with a timeout, the timeout could be the same as the sleep time before stopping.

### PR DESCRIPTION
**Pull request by YuJuncen**
### What problem does this PR solve? 
fix #557
This PR also added a guard for the `glue.Progress` implement, to prevent the `send on close channel` panics.

### What is changed and how it works?
see #557 

### Check List 

Tests 

 - Integration test

### Release Note

 - Fixed a bug that caused BR won't do cleanup tasks when receiving SIGTERM.

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -30,14 +30,7 @@ func main() {
...
 		log.Warn("received signal to exit", zap.Stringer("signal", sig))
-		switch sig {
-		case syscall.SIGTERM:
-			cancel()
-			os.Exit(0)
-		default:
-			cancel()
-			os.Exit(1)
-		}
+		cancel()
```
Comment (overvenus) [inline main.go:33]: What about trying to graceful shutdown at the first time BR receives signal, and os.Exit() when it receives signal twice? So we can avoid hard code 30 seconds timeout.

Comment (YuJuncen) [reply main.go:33]: Good idea!

Comment (YuJuncen) [reply main.go:33]: Done, PTAL~

File: Makefile [hunk 2]
```diff
@@ -121,10 +121,12 @@ lint: tools
 	CGO_ENABLED=0 tools/bin/revive -formatter friendly -config revive.toml $$($(PACKAGES))
 
 tidy: prepare
+	# tidy isn't a read-only task for go.mod, run FINISH_MOD always, 
+	# so our go.mod1 won't stick in old state
+	trap "$(FINISH_MOD)" EXIT
```
Comment (kennytm) [inline Makefile:126]: this `trap` likely won't work, since every line in the makefile starts a new shell.

Comment (YuJuncen) [reply Makefile:126]: Oops... So it's a little hard to gracefully run it...

File: pkg/gluetikv/glue.go [hunk 3]
```diff
@@ -5,10 +5,13 @@ package gluetikv
 import (
 	"context"
 
+	"sync/atomic"
```
Comment (overvenus) [inline pkg/gluetikv/glue.go:8]:
```suggestion
	"context"
	"sync/atomic"
```

File: pkg/task/restore.go [hunk 4]
```diff
@@ -367,6 +367,10 @@ func restorePreWork(ctx context.Context, client *restore.Client, mgr *conn.Mgr)
 func restorePostWork(
 	ctx context.Context, client *restore.Client, restoreSchedulers utils.UndoFunc,
 ) {
+	if ctx.Err() != nil {
+		log.Warn("context canceled, doing clean work with background context")
```
Comment (overvenus) [inline pkg/task/restore.go:371]:
```suggestion
		log.Warn("context canceled, try shutdown")
```

File: pkg/task/backup_raw.go [hunk 5]
```diff
@@ -147,6 +147,10 @@ func RunBackupRaw(c context.Context, g glue.Glue, cmdName string, cfg *RawKvConf
 	if cfg.RemoveSchedulers {
 		restore, e := mgr.RemoveSchedulers(ctx)
 		defer func() {
+			if ctx.Err() != nil {
+				log.Warn("context canceled, doing clean work with background context")
```
Comment (overvenus) [inline pkg/task/backup_raw.go:151]:
```suggestion
				log.Warn("context canceled, try shutdown")
```

**Review by overvenus — APPROVED** [review]
Rest LGTM

File: main.go [hunk 6]
```diff
@@ -30,14 +30,12 @@ func main() {
...
+		fmt.Println("gracefully shuting down, press ^C again to force exit")
```
Comment (kennytm) [inline main.go:34]: print to stderr please.

```suggestion
		fmt.Fprintln(os.Stderr, "gracefully shuting down, press ^C again to force exit")
```

File: pkg/gluetikv/glue.go [hunk 7]
```diff
@@ -57,15 +60,28 @@ func (Glue) Record(name string, val uint64) {
...
+	if atomic.LoadInt32(&p.closed) != 0 {
+		log.Warn("proposing a closed progress")
+		return
+	}
+	// there might be buggy if the thread is yielded here.
+	// however, there should not be gosched, at most time.
+	// so send here probably is safe, even not totally safe.
+	// since adding an extra lock should be costly, we just be optimistic.
+	// (Maybe a spin lock here would be better?)
 	p.ch <- struct{}{}
```
Comment (kennytm) [inline pkg/gluetikv/glue.go:78]: it is possible to just make this entire progress structure an atomic integer instead of a channel, like https://github.com/pingcap/tidb/blob/c7651f02be36b5faf95a204d20f8859eb9c2080a/executor/brie.go#L49-L73? tbh i don't see any reason why we use a channel in the first place, since we're using a 1-second timer to update the progress bar in any case.

Comment (YuJuncen) [reply pkg/gluetikv/glue.go:77]: well there would be more change than this pr itself if we refactor the progess struct here. how about leaving a TODO here and leave it another PR?

Comment (YuJuncen) [reply pkg/gluetikv/glue.go:77]: (But I could have a try this PR, anyway)

**Review by kennytm — COMMENTED** [review]
lgtm

**Review by ti-srebot — APPROVED** [review]
