### PR TITLE
lightning/restore: fail fast when met error in engine/chunk restore

### LINKED ISSUE #765: Test lightning_checkpoint_engines fails
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
[2021-02-26T17:33:40.431Z] Error: checksum mismatched remote vs local => (checksum: 2776093422133432446 vs 3203001050118138354) (total_kvs: 2 vs 4) (total_bytes:58 vs 116)
[2021-02-26T17:33:40.431Z] tidb lightning encountered error:  checksum mismatched remote vs local => (checksum: 2776093422133432446 vs 3203001050118138354) (total_kvs: 2 vs 4) (total_bytes:58 vs 116)
```

2. What did you expect to see?

Pass the tests

3. What did you see instead?

Fails.

5. Operation logs

<details> <summary>Log</summary>

```
[2021-02-26T17:31:47.867Z] + rm -rf /tmp/backup_restore_test

[2021-02-26T17:31:47.867Z] + mkdir -p /tmp/backup_restore_test

[2021-02-26T17:31:47.867Z] + rm -rf cover

[2021-02-26T17:31:47.867Z] + mkdir cover

[2021-02-26T17:31:47.867Z] + [[ ! -e tests/lightning_checkpoint_engines/run.sh ]]

[2021-02-26T17:31:47.867Z] + export GOPATH=/go:/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go

[2021-02-26T17:31:47.867Z] + GOPATH=/go:/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go

[2021-02-26T17:31:47.867Z] + export PATH=/go:/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/bin:/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

[2021-02-26T17:31:47.867Z] + PATH=/go:/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/bin:/home/jenkins/agent/workspace/br_ghpr_unit_and_integration_test/go/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

[2021-02-26T17:31:47.867Z] + TEST_NAME=lightning_checkpoint_engines

[2021-02-26T17:31:47.867Z] + tests/run.sh

[2021-02-26T17:31:50.418Z] Starting PD...

[2021-02-26T17:32:00.361Z] {

[2021-02-26T17:32:00.361Z]   "version": "v4.0.0-rc.2-464-g1f200cbc"

[2021-02-26T17:32:00.361Z] }

[2021-02-26T17:32:00.361Z] Starting TiKV...

[2021-02-26T17:32:00.361Z] Waiting initializing TiKV...

[2021-02-26T17:32:15.311Z]   "is_initialized": true,

[2021-02-26T17:32:15.311Z] Starting TiDB...

[2021-02-26T17:32:15.311Z] Verifying TiDB is started...

[2021-02-26T17:33:22.955Z] {"connections":0,"version":"5.7.25-TiDB-v4.0.0-beta.2-2205-g53a68b56d","git_hash":"53a68b56da072c6b9863ce38b4488ede618cfd49"}Starting Importer...

[2021-02-26T17:33:22.955Z] Starting TiFlash...

[2021-02-26T17:33:22.955Z] TiFlash seems doesn't started, retrying...

[2021-02-26T17:33:22.955Z] Logging trace to /tmp/backup_restore_test/tiflash-stdout.log

[2021-02-26T17:33:22.955Z] Logging errors to /tmp/backup_restore_test/tiflash-stderr.log

[2021-02-26T17:33:22.955Z] TiFlash started.

[2021-02-26T17:33:22.955Z] selected test cases: lightning_checkpoint_engines

[2021-02-26T17:33:22.955Z] *===== Running test tests/lightning_checkpoint_engines/run.sh... =====*

[2021-02-26T17:33:22.955Z] + for BACKEND in importer local

[2021-02-26T17:33:22.955Z] + '[' importer = local ']'

[2021-02-26T17:33:22.955Z] + rm -f /tmp/backup_restore_test/lightning-checkpoint-engines.log

[2021-02-26T17:33:22.955Z] + rm -f /tmp/tidb_lightning_checkpoint.pb

[2021-02-26T17:33:22.955Z] + run_sql 'DROP DATABASE IF EXISTS cpeng;'

[2021-02-26T17:33:22.955Z] + export GO_FAILPOINTS=

[2021-02-26T17:33:22.955Z] + GO_FAILPOINTS=

[2021-02-26T17:33:22.955Z] + do_run_lightning importer config

[2021-02-26T17:33:22.955Z] + run_lightning --backend importer --enable-checkpoint=1 --log-file /tmp/backup_restore_test/lightning-checkpoint-engines.log --config tests/lightning_checkpoint_engines/config.toml

[2021-02-26T17:33:22.955Z] ++ date

[2021-02-26T17:33:22.955Z] + echo '[Sat Feb 27 01:33:20 CST 2021] <<<<<< RUNNING TEST FOR: tests/lightning_checkpoint_engines --backend' importer --enable-checkpoint=1 --log-file /tmp/backup_restore_test/lightning-checkpoint-engines.log --config 'tests/lightning_checkpoint_engines/config.toml >>>>>>'

[2021-02-26T17:33:22.955Z] + bin/tidb-lightning.test -test.coverprofile=/tmp/backup_restore_test/cov.lightning_checkpoint_engines.1456.out DEVEL --ca /tmp/backup_restore_test/certs/ca.pem --cert /tmp/backup_restore_test/certs/lightning.pem --key /tmp/backup_restore_test/certs/lightning.key --log-file /tmp/backup_restore_test/lightning.log --tidb-port 4000 --pd-urls 127.0.0.1:2379 --config tests/lightning_checkpoint_engines/config.toml -d tests/lightning_checkpoint_engines/data --importer 127.0.0.1:8808 --sorted-kv-dir /tmp/backup_restore_test/lightning_checkpoint_engines.sorted --enable-checkpoint=0 --check-requirements=0 --backend importer --enable-checkpoint=1 --log-file /tmp/backup_restore_test/lightning-checkpoint-engines.log --config tests/lightning_checkpoint_engines/config.toml

[2021-02-26T17:33:22.955Z] Verbose debug logs will be written to /tmp/backup_restore_test/lightning-checkpoint-engines.log

[2021-02-26T17:33:22.955Z] 

[2021-02-26T17:33:22.955Z] [2021/02/27 01:33:21.073 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:22.955Z] [2021/02/27 01:33:21.079 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:22.955Z] [2021/02/27 01:33:21.079 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:22.955Z] [2021/02/27 01:33:21.080 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:22.955Z] [2021/02/27 01:33:21.080 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:22.955Z] [2021/02/27 01:33:21.087 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:22.955Z] [2021/02/27 01:33:21.087 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:22.955Z] [2021/02/27 01:33:21.088 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:22.955Z] tidb lightning exit

[2021-02-26T17:33:22.955Z] PASS

[2021-02-26T17:33:22.955Z] coverage: 17.8% of statements in github.com/pingcap/br/...

[2021-02-26T17:33:22.955Z] + DATA_ENGINE_COUNT=4

[2021-02-26T17:33:22.955Z] + INDEX_ENGINE_COUNT=2

[2021-02-26T17:33:22.955Z] + ENGINE_COUNT=6

[2021-02-26T17:33:22.955Z] ++ grep 'open engine' /tmp/backup_restore_test/lightning-checkpoint-engines.log

[2021-02-26T17:33:22.955Z] ++ wc -l

[2021-02-26T17:33:22.955Z] + OPEN_ENGINES_COUNT=6

[2021-02-26T17:33:22.955Z] + echo 'Number of open engines: 6'

[2021-02-26T17:33:22.955Z] Number of open engines: 6

[2021-02-26T17:33:22.955Z] + '[' 6 -eq 6 ']'

[2021-02-26T17:33:22.955Z] + run_sql 'SELECT count(*), sum(c) FROM cpeng.a'

[2021-02-26T17:33:22.955Z] *************************** 1. row ***************************

[2021-02-26T17:33:22.955Z] count(*): 4

[2021-02-26T17:33:22.955Z]   sum(c): 10

[2021-02-26T17:33:22.955Z] + check_contains 'count(*): 4'

[2021-02-26T17:33:22.955Z] + check_contains 'sum(c): 10'

[2021-02-26T17:33:22.955Z] + run_sql 'SELECT count(*), sum(c) FROM cpeng.b'

[2021-02-26T17:33:22.955Z] *************************** 1. row ***************************

[2021-02-26T17:33:22.955Z] count(*): 4

[2021-02-26T17:33:22.955Z]   sum(c): 46

[2021-02-26T17:33:22.955Z] + check_contains 'count(*): 4'

[2021-02-26T17:33:22.955Z] + check_contains 'sum(c): 46'

[2021-02-26T17:33:22.955Z] + run_sql 'DROP DATABASE cpeng;'

[2021-02-26T17:33:22.955Z] + rm -f /tmp/tidb_lightning_checkpoint.pb

[2021-02-26T17:33:22.955Z] + export 'GO_FAILPOINTS=github.com/pingcap/br/pkg/lightning/restore/SlowDownImport=sleep(500);github.com/pingcap/br/pkg/lightning/restore/FailIfStatusBecomes=return(120);github.com/pingcap/br/pkg/lightning/restore/FailIfIndexEngineImported=return(140)'

[2021-02-26T17:33:22.955Z] + GO_FAILPOINTS='github.com/pingcap/br/pkg/lightning/restore/SlowDownImport=sleep(500);github.com/pingcap/br/pkg/lightning/restore/FailIfStatusBecomes=return(120);github.com/pingcap/br/pkg/lightning/restore/FailIfIndexEngineImported=return(140)'

[2021-02-26T17:33:22.955Z] + set +e

[2021-02-26T17:33:22.955Z] ++ seq 6

[2021-02-26T17:33:22.955Z] + for i in '$(seq "$ENGINE_COUNT")'

[2021-02-26T17:33:22.955Z] + echo '******** Importing Table Now (step 1/6) ********'

[2021-02-26T17:33:22.955Z] ******** Importing Table Now (step 1/6) ********

[2021-02-26T17:33:22.955Z] + do_run_lightning importer config

[2021-02-26T17:33:22.955Z] Verbose debug logs will be written to /tmp/backup_restore_test/lightning-checkpoint-engines.log

[2021-02-26T17:33:22.955Z] 

[2021-02-26T17:33:23.212Z] [2021/02/27 01:33:22.991 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:23.212Z] [2021/02/27 01:33:22.996 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:23.212Z] [2021/02/27 01:33:22.997 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:23.212Z] [2021/02/27 01:33:22.997 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:23.212Z] [2021/02/27 01:33:22.997 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:23.212Z] [2021/02/27 01:33:23.003 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:23.213Z] [2021/02/27 01:33:23.003 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:23.213Z] [2021/02/27 01:33:23.003 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:23.213Z] + '[' 2 -ne 0 ']'

[2021-02-26T17:33:23.213Z] + for i in '$(seq "$ENGINE_COUNT")'

[2021-02-26T17:33:23.213Z] + echo '******** Importing Table Now (step 2/6) ********'

[2021-02-26T17:33:23.213Z] ******** Importing Table Now (step 2/6) ********

[2021-02-26T17:33:23.213Z] + do_run_lightning importer config

[2021-02-26T17:33:23.489Z] Verbose debug logs will be written to /tmp/backup_restore_test/lightning-checkpoint-engines.log

[2021-02-26T17:33:23.489Z] 

[2021-02-26T17:33:23.746Z] [2021/02/27 01:33:23.722 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:23.746Z] [2021/02/27 01:33:23.728 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:23.746Z] [2021/02/27 01:33:23.728 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:23.746Z] [2021/02/27 01:33:23.728 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:23.746Z] [2021/02/27 01:33:23.728 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:23.746Z] [2021/02/27 01:33:23.734 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:23.746Z] [2021/02/27 01:33:23.734 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:23.746Z] [2021/02/27 01:33:23.734 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:24.020Z] + '[' 2 -ne 0 ']'

[2021-02-26T17:33:24.021Z] + for i in '$(seq "$ENGINE_COUNT")'

[2021-02-26T17:33:24.021Z] + echo '******** Importing Table Now (step 3/6) ********'

[2021-02-26T17:33:24.021Z] ******** Importing Table Now (step 3/6) ********

[2021-02-26T17:33:24.021Z] + do_run_lightning importer config

[2021-02-26T17:33:24.021Z] Verbose debug logs will be written to /tmp/backup_restore_test/lightning-checkpoint-engines.log

[2021-02-26T17:33:24.021Z] 

[2021-02-26T17:33:24.600Z] [2021/02/27 01:33:24.328 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:24.600Z] [2021/02/27 01:33:24.336 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:24.600Z] [2021/02/27 01:33:24.336 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:24.600Z] [2021/02/27 01:33:24.336 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:24.600Z] [2021/02/27 01:33:24.336 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:24.600Z] [2021/02/27 01:33:24.342 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:24.600Z] [2021/02/27 01:33:24.342 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:24.600Z] [2021/02/27 01:33:24.342 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:24.600Z] + '[' 2 -ne 0 ']'

[2021-02-26T17:33:24.600Z] + for i in '$(seq "$ENGINE_COUNT")'

[2021-02-26T17:33:24.600Z] + echo '******** Importing Table Now (step 4/6) ********'

[2021-02-26T17:33:24.600Z] ******** Importing Table Now (step 4/6) ********

[2021-02-26T17:33:24.600Z] + do_run_lightning importer config

[2021-02-26T17:33:24.600Z] Verbose debug logs will be written to /tmp/backup_restore_test/lightning-checkpoint-engines.log

[2021-02-26T17:33:24.600Z] 

[2021-02-26T17:33:25.166Z] [2021/02/27 01:33:24.883 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:25.166Z] [2021/02/27 01:33:24.892 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:25.166Z] [2021/02/27 01:33:24.892 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:25.166Z] [2021/02/27 01:33:24.893 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:25.166Z] [2021/02/27 01:33:24.893 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:25.166Z] [2021/02/27 01:33:24.899 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:25.166Z] [2021/02/27 01:33:24.899 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:25.166Z] [2021/02/27 01:33:24.900 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:25.166Z] + '[' 2 -ne 0 ']'

[2021-02-26T17:33:25.166Z] + for i in '$(seq "$ENGINE_COUNT")'

[2021-02-26T17:33:25.166Z] + echo '******** Importing Table Now (step 5/6) ********'

[2021-02-26T17:33:25.166Z] ******** Importing Table Now (step 5/6) ********

[2021-02-26T17:33:25.166Z] + do_run_lightning importer config

[2021-02-26T17:33:25.166Z] Verbose debug logs will be written to /tmp/backup_restore_test/lightning-checkpoint-engines.log

[2021-02-26T17:33:25.166Z] 

[2021-02-26T17:33:25.737Z] [2021/02/27 01:33:25.468 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:25.737Z] [2021/02/27 01:33:25.475 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:25.737Z] [2021/02/27 01:33:25.475 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:25.737Z] [2021/02/27 01:33:25.475 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:25.737Z] [2021/02/27 01:33:25.475 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:25.737Z] [2021/02/27 01:33:25.482 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:25.737Z] [2021/02/27 01:33:25.482 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:25.737Z] [2021/02/27 01:33:25.483 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:25.737Z] [2021/02/27 01:33:25.484 +08:00] [INFO] [client.go:591] ["[pd] tso dispatcher is not ready, wait for a while"]

[2021-02-26T17:33:25.737Z] [2021/02/27 01:33:25.534 +08:00] [WARN] [pd.go:131] ["get timestamp too slow"] ["cost time"=50.750507ms]

[2021-02-26T17:33:26.326Z] + '[' 2 -ne 0 ']'

[2021-02-26T17:33:26.326Z] + for i in '$(seq "$ENGINE_COUNT")'

[2021-02-26T17:33:26.326Z] + echo '******** Importing Table Now (step 6/6) ********'

[2021-02-26T17:33:26.326Z] ******** Importing Table Now (step 6/6) ********

[2021-02-26T17:33:26.326Z] + do_run_lightning importer config

[2021-02-26T17:33:26.326Z] Verbose debug logs will be written to /tmp/backup_restore_test/lightning-checkpoint-engines.log

[2021-02-26T17:33:26.326Z] 

[2021-02-26T17:33:26.894Z] [2021/02/27 01:33:26.682 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:26.894Z] [2021/02/27 01:33:26.691 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:26.894Z] [2021/02/27 01:33:26.691 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:26.894Z] [2021/02/27 01:33:26.692 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:26.894Z] [2021/02/27 01:33:26.692 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:26.894Z] [2021/02/27 01:33:26.699 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:26.894Z] [2021/02/27 01:33:26.699 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:26.894Z] [2021/02/27 01:33:26.700 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:27.475Z] + '[' 2 -ne 0 ']'

[2021-02-26T17:33:27.475Z] + set -e

[2021-02-26T17:33:27.475Z] + echo '******** Verify checkpoint no-op ********'

[2021-02-26T17:33:27.475Z] ******** Verify checkpoint no-op ********

[2021-02-26T17:33:27.475Z] + do_run_lightning importer config

[2021-02-26T17:33:27.475Z] + run_lightning --backend importer --enable-checkpoint=1 --log-file /tmp/backup_restore_test/lightning-checkpoint-engines.log --config tests/lightning_checkpoint_engines/config.toml

[2021-02-26T17:33:27.475Z] ++ date

[2021-02-26T17:33:27.475Z] + echo '[Sat Feb 27 01:33:27 CST 2021] <<<<<< RUNNING TEST FOR: tests/lightning_checkpoint_engines --backend' importer --enable-checkpoint=1 --log-file /tmp/backup_restore_test/lightning-checkpoint-engines.log --config 'tests/lightning_checkpoint_engines/config.toml >>>>>>'

[2021-02-26T17:33:27.475Z] + bin/tidb-lightning.test -test.coverprofile=/tmp/backup_restore_test/cov.lightning_checkpoint_engines.3415.out DEVEL --ca /tmp/backup_restore_test/certs/ca.pem --cert /tmp/backup_restore_test/certs/lightning.pem --key /tmp/backup_restore_test/certs/lightning.key --log-file /tmp/backup_restore_test/lightning.log --tidb-port 4000 --pd-urls 127.0.0.1:2379 --config tests/lightning_checkpoint_engines/config.toml -d tests/lightning_checkpoint_engines/data --importer 127.0.0.1:8808 --sorted-kv-dir /tmp/backup_restore_test/lightning_checkpoint_engines.sorted --enable-checkpoint=0 --check-requirements=0 --backend importer --enable-checkpoint=1 --log-file /tmp/backup_restore_test/lightning-checkpoint-engines.log --config tests/lightning_checkpoint_engines/config.toml

[2021-02-26T17:33:27.475Z] Verbose debug logs will be written to /tmp/backup_restore_test/lightning-checkpoint-engines.log

[2021-02-26T17:33:27.476Z] 

[2021-02-26T17:33:27.764Z] [2021/02/27 01:33:27.772 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:28.067Z] [2021/02/27 01:33:27.781 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:28.067Z] [2021/02/27 01:33:27.781 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:28.067Z] [2021/02/27 01:33:27.781 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:28.067Z] [2021/02/27 01:33:27.781 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:28.067Z] [2021/02/27 01:33:27.788 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:28.067Z] [2021/02/27 01:33:27.788 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:28.067Z] [2021/02/27 01:33:27.789 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:28.067Z] [2021/02/27 01:33:27.790 +08:00] [INFO] [client.go:591] ["[pd] tso dispatcher is not ready, wait for a while"]

[2021-02-26T17:33:28.067Z] [2021/02/27 01:33:27.840 +08:00] [WARN] [pd.go:131] ["get timestamp too slow"] ["cost time"=50.734409ms]

[2021-02-26T17:33:28.067Z] tidb lightning exit

[2021-02-26T17:33:28.067Z] PASS

[2021-02-26T17:33:28.339Z] coverage: 16.6% of statements in github.com/pingcap/br/...

[2021-02-26T17:33:28.339Z] + run_sql 'SELECT count(*), sum(c) FROM cpeng.a'

[2021-02-26T17:33:28.339Z] *************************** 1. row ***************************

[2021-02-26T17:33:28.339Z] count(*): 4

[2021-02-26T17:33:28.339Z]   sum(c): 10

[2021-02-26T17:33:28.339Z] + check_contains 'count(*): 4'

[2021-02-26T17:33:28.339Z] + check_contains 'sum(c): 10'

[2021-02-26T17:33:28.339Z] + run_sql 'SELECT count(*), sum(c) FROM cpeng.b'

[2021-02-26T17:33:28.339Z] *************************** 1. row ***************************

[2021-02-26T17:33:28.339Z] count(*): 4

[2021-02-26T17:33:28.339Z]   sum(c): 46

[2021-02-26T17:33:28.339Z] + check_contains 'count(*): 4'

[2021-02-26T17:33:28.339Z] + check_contains 'sum(c): 46'

[2021-02-26T17:33:28.339Z] + run_sql 'DROP DATABASE cpeng;'

[2021-02-26T17:33:28.614Z] + run_sql 'DROP DATABASE IF EXISTS tidb_lightning_checkpoint;'

[2021-02-26T17:33:28.614Z] + set +e

[2021-02-26T17:33:28.614Z] ++ seq 6

[2021-02-26T17:33:28.614Z] + for i in '$(seq "$ENGINE_COUNT")'

[2021-02-26T17:33:28.614Z] + echo '******** Importing Table Now (step 1/6) ********'

[2021-02-26T17:33:28.614Z] ******** Importing Table Now (step 1/6) ********

[2021-02-26T17:33:28.614Z] + do_run_lightning importer mysql

[2021-02-26T17:33:28.614Z] Verbose debug logs will be written to /tmp/backup_restore_test/lightning-checkpoint-engines.log

[2021-02-26T17:33:28.614Z] 

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:35.454 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:35.461 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:35.461 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:35.461 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:35.461 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:35.466 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:35.466 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:35.466 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:36.733Z] + '[' 2 -ne 0 ']'

[2021-02-26T17:33:36.733Z] + for i in '$(seq "$ENGINE_COUNT")'

[2021-02-26T17:33:36.733Z] + echo '******** Importing Table Now (step 2/6) ********'

[2021-02-26T17:33:36.733Z] ******** Importing Table Now (step 2/6) ********

[2021-02-26T17:33:36.733Z] + do_run_lightning importer mysql

[2021-02-26T17:33:36.733Z] Verbose debug logs will be written to /tmp/backup_restore_test/lightning-checkpoint-engines.log

[2021-02-26T17:33:36.733Z] 

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:36.040 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:36.046 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:36.046 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:36.047 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:36.047 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:36.051 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:36.051 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:36.052 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:36.733Z] + '[' 2 -ne 0 ']'

[2021-02-26T17:33:36.733Z] + for i in '$(seq "$ENGINE_COUNT")'

[2021-02-26T17:33:36.733Z] + echo '******** Importing Table Now (step 3/6) ********'

[2021-02-26T17:33:36.733Z] ******** Importing Table Now (step 3/6) ********

[2021-02-26T17:33:36.733Z] + do_run_lightning importer mysql

[2021-02-26T17:33:36.733Z] Verbose debug logs will be written to /tmp/backup_restore_test/lightning-checkpoint-engines.log

[2021-02-26T17:33:36.733Z] 

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:36.574 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:36.580 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:36.580 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:36.580 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:36.580 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:36.585 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:36.585 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:36.733Z] [2021/02/27 01:33:36.586 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:36.733Z] + '[' 2 -ne 0 ']'

[2021-02-26T17:33:36.733Z] + for i in '$(seq "$ENGINE_COUNT")'

[2021-02-26T17:33:36.733Z] + echo '******** Importing Table Now (step 4/6) ********'

[2021-02-26T17:33:36.733Z] ******** Importing Table Now (step 4/6) ********

[2021-02-26T17:33:36.733Z] + do_run_lightning importer mysql

[2021-02-26T17:33:36.989Z] Verbose debug logs will be written to /tmp/backup_restore_test/lightning-checkpoint-engines.log

[2021-02-26T17:33:36.989Z] 

[2021-02-26T17:33:37.247Z] [2021/02/27 01:33:37.155 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:37.247Z] [2021/02/27 01:33:37.162 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:37.247Z] [2021/02/27 01:33:37.162 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:37.247Z] [2021/02/27 01:33:37.162 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:37.247Z] [2021/02/27 01:33:37.162 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:37.247Z] [2021/02/27 01:33:37.167 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:37.247Z] [2021/02/27 01:33:37.167 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:37.247Z] [2021/02/27 01:33:37.168 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:38.183Z] + '[' 2 -ne 0 ']'

[2021-02-26T17:33:38.183Z] + for i in '$(seq "$ENGINE_COUNT")'

[2021-02-26T17:33:38.183Z] + echo '******** Importing Table Now (step 5/6) ********'

[2021-02-26T17:33:38.183Z] ******** Importing Table Now (step 5/6) ********

[2021-02-26T17:33:38.183Z] + do_run_lightning importer mysql

[2021-02-26T17:33:38.183Z] Verbose debug logs will be written to /tmp/backup_restore_test/lightning-checkpoint-engines.log

[2021-02-26T17:33:38.183Z] 

[2021-02-26T17:33:38.470Z] [2021/02/27 01:33:38.339 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:38.470Z] [2021/02/27 01:33:38.345 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:38.470Z] [2021/02/27 01:33:38.345 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:38.470Z] [2021/02/27 01:33:38.345 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:38.471Z] [2021/02/27 01:33:38.345 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:38.471Z] [2021/02/27 01:33:38.351 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:38.471Z] [2021/02/27 01:33:38.351 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:38.471Z] [2021/02/27 01:33:38.351 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:38.728Z] + '[' 2 -ne 0 ']'

[2021-02-26T17:33:38.728Z] + for i in '$(seq "$ENGINE_COUNT")'

[2021-02-26T17:33:38.728Z] + echo '******** Importing Table Now (step 6/6) ********'

[2021-02-26T17:33:38.728Z] ******** Importing Table Now (step 6/6) ********

[2021-02-26T17:33:38.728Z] + do_run_lightning importer mysql

[2021-02-26T17:33:38.728Z] Verbose debug logs will be written to /tmp/backup_restore_test/lightning-checkpoint-engines.log

[2021-02-26T17:33:38.728Z] 

[2021-02-26T17:33:38.986Z] [2021/02/27 01:33:38.927 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:38.986Z] [2021/02/27 01:33:38.932 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:38.986Z] [2021/02/27 01:33:38.932 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:38.986Z] [2021/02/27 01:33:38.933 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:38.986Z] [2021/02/27 01:33:38.933 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:38.986Z] [2021/02/27 01:33:38.937 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:38.986Z] [2021/02/27 01:33:38.938 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:38.986Z] [2021/02/27 01:33:38.938 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:39.918Z] + '[' 2 -ne 0 ']'

[2021-02-26T17:33:39.918Z] + set -e

[2021-02-26T17:33:39.918Z] + echo '******** Verify checkpoint no-op ********'

[2021-02-26T17:33:39.918Z] ******** Verify checkpoint no-op ********

[2021-02-26T17:33:39.918Z] + do_run_lightning importer mysql

[2021-02-26T17:33:39.918Z] + run_lightning --backend importer --enable-checkpoint=1 --log-file /tmp/backup_restore_test/lightning-checkpoint-engines.log --config tests/lightning_checkpoint_engines/mysql.toml

[2021-02-26T17:33:39.918Z] ++ date

[2021-02-26T17:33:39.918Z] + echo '[Sat Feb 27 01:33:39 CST 2021] <<<<<< RUNNING TEST FOR: tests/lightning_checkpoint_engines --backend' importer --enable-checkpoint=1 --log-file /tmp/backup_restore_test/lightning-checkpoint-engines.log --config 'tests/lightning_checkpoint_engines/mysql.toml >>>>>>'

[2021-02-26T17:33:39.918Z] + bin/tidb-lightning.test -test.coverprofile=/tmp/backup_restore_test/cov.lightning_checkpoint_engines.4543.out DEVEL --ca /tmp/backup_restore_test/certs/ca.pem --cert /tmp/backup_restore_test/certs/lightning.pem --key /tmp/backup_restore_test/certs/lightning.key --log-file /tmp/backup_restore_test/lightning.log --tidb-port 4000 --pd-urls 127.0.0.1:2379 --config tests/lightning_checkpoint_engines/config.toml -d tests/lightning_checkpoint_engines/data --importer 127.0.0.1:8808 --sorted-kv-dir /tmp/backup_restore_test/lightning_checkpoint_engines.sorted --enable-checkpoint=0 --check-requirements=0 --backend importer --enable-checkpoint=1 --log-file /tmp/backup_restore_test/lightning-checkpoint-engines.log --config tests/lightning_checkpoint_engines/mysql.toml

[2021-02-26T17:33:39.918Z] Verbose debug logs will be written to /tmp/backup_restore_test/lightning-checkpoint-engines.log

[2021-02-26T17:33:39.918Z] 

[2021-02-26T17:33:40.175Z] [2021/02/27 01:33:39.993 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:40.175Z] [2021/02/27 01:33:40.000 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:40.175Z] [2021/02/27 01:33:40.000 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:40.175Z] [2021/02/27 01:33:40.000 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:40.175Z] [2021/02/27 01:33:40.000 +08:00] [INFO] [client.go:194] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]

[2021-02-26T17:33:40.175Z] [2021/02/27 01:33:40.005 +08:00] [INFO] [base_client.go:296] ["[pd] update member urls"] [old-urls="[http://127.0.0.1:2379]"] [new-urls="[https://127.0.0.1:2379]"]

[2021-02-26T17:33:40.175Z] [2021/02/27 01:33:40.005 +08:00] [INFO] [base_client.go:308] ["[pd] switch leader"] [new-leader=https://127.0.0.1:2379] [old-leader=]

[2021-02-26T17:33:40.175Z] [2021/02/27 01:33:40.006 +08:00] [INFO] [base_client.go:112] ["[pd] init cluster id"] [cluster-id=6933626468177358442]

[2021-02-26T17:33:40.431Z] Error: checksum mismatched remote vs local => (checksum: 2776093422133432446 vs 3203001050118138354) (total_kvs: 2 vs 4) (total_bytes:58 vs 116)

[2021-02-26T17:33:40.431Z] tidb lightning encountered error:  checksum mismatched remote vs local => (checksum: 2776093422133432446 vs 3203001050118138354) (total_kvs: 2 vs 4) (total_bytes:58 vs 116)

[2021-02-26T17:33:42.324Z] tests/_utils/run_services: line 40:   952 Killed                  bin/tidb-server -P 4000 --status 10080 --advertise-address="127.0.0.1" --store tikv --path "$PD_ADDR" --config "$TIDB_CONFIG" --log-file "$TEST_DIR/tidb.log"

[2021-02-26T17:33:43.255Z] tests/_utils/run_services: line 40:  1102 Killed                  LD_LIBRARY_PATH=bin/ bin/tiflash server --config-file="$TEST_DIR/tiflash.toml"

[2021-02-26T17:33:43.255Z] {"level":"warn","ts":"2021-02-27T01:33:43.251+0800","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-fefcb7cb-e424-4753-80cf-3fa37f468c1c/127.0.0.1:2379","attempt":0,"error":"rpc error: code = NotFound desc = etcdserver: requested lease not found"}
```

</details>

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/4970/pipeline/#step-1007-log-320

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
- Stop all the other chunk/engine tasks fast if met error in one chunk/engine task.
- avoid retrying and printing error log if the error is context canceled
- This pr also fix a bug that `deliverLoop` ingnores the error that WriteRows return. This should close #765 

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Release Note

 - fail fast when lightning meets error in engine/chunk restore and do not retry `context.Cancel` error

### CODE REVIEW

File: tests/lightning_fail_fast/run.sh [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+for CFG in chunk engine; do
+  rm -f "$TEST_DIR/lightning-tidb.log"
+  run_sql 'DROP DATABASE IF EXISTS fail_fast;'
+
+  set +e
+  run_lightning --backend tidb --enable-checkpoint=0 --log-file "$TEST_DIR/lightning-tidb.log" --config "tests/$TEST_NAME/$CFG.toml"
+  ERRORCODE=$?
+  set -e
+
+  [ "$ERRORCODE" -ne 0 ]
```
Comment (YuJuncen) [inline tests/lightning_fail_fast/run.sh:29]: Why not?

```suggestion
  ! run_lightning --backend tidb --enable-checkpoint=0 --log-file "$TEST_DIR/lightning-tidb.log" --config "tests/$TEST_NAME/$CFG.toml"
```

**Comment by glorv** [comment]
@YuJuncen @kennytm PTAL again

File: pkg/lightning/restore/restore.go [hunk 2]
```diff
@@ -2292,7 +2303,7 @@ func (cr *chunkRestore) deliverLoop(
 			saveCheckpoint(rc, t, engineID, cr.chunk)
 		}
 
-		func() {
+		err = func() error {
```
Comment (YuJuncen) [inline pkg/lightning/restore/restore.go:2306]: If time is enough, I think we might should make a refactor on `restoreEngine`. (Not for now, yes.)

IMO, Using control flow like this seems a little weird...

File: tests/lightning_fail_fast/run.sh (hunk 1 above)
Comment (kennytm) [reply tests/lightning_fail_fast/run.sh]: @YuJuncen i don't think it works.

```sh
#!/bin/bash
set -eu
true
echo 'should print this because `true`'
! false
echo 'should print this because `! false` == `true`'
! true
echo 'should not print this because `! true` == `false`'
false
echo 'should not print this because `false`'
```

```
should print this because `true`
should print this because `! false` == `true`
should not print this because `! true` == `false`
```

Comment (YuJuncen) [reply tests/lightning_fail_fast/run.sh]: @kennytm Well, bash is awesome. 🙃
So, we need to change those two `greps` below too, right?

Comment (kennytm) [reply tests/lightning_fail_fast/run.sh]: @YuJuncen no need to change the grep, the handling of error code is correct (note 0 = true, 1 = false):

```sh
#!/bin/bash
set -eu
true
echo $?, 'should print this because `true`'
! false
echo $?, 'should print this because `! false` == `true`'
! true
echo $?, 'should not print this because `! true` == `false`'
false
echo $?, 'should not print this because `false`'
```

```
0, should print this because `true`
0, should print this because `! false` == `true`
1, should not print this because `! true` == `false`
```

Comment (YuJuncen) [reply tests/lightning_fail_fast/run.sh]: @kennytm I mean these lines.

https://github.com/pingcap/br/blob/b5925e7ff7673b582fc29a6f18dc8f4d3108f386/tests/lightning_fail_fast/run.sh#L27-L28

Seems the return code isn't used here.

Comment (kennytm) [reply tests/lightning_fail_fast/run.sh]: oh. well yeah.

File: tests/lightning_fail_fast/run.sh [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+
+set -eux
+
+export GO_FAILPOINTS='github.com/pingcap/br/pkg/lightning/restore/SlowDownWriteRows=sleep(50);github.com/pingcap/br/pkg/lightning/restore/SetMinDeliverBytes=return(1)'
+
+for CFG in chunk engine; do
+  rm -f "$TEST_DIR/lightning-tidb.log"
+  run_sql 'DROP DATABASE IF EXISTS fail_fast;'
+
+  ! run_lightning --backend tidb --enable-checkpoint=0 --log-file "$TEST_DIR/lightning-tidb.log" --config "tests/$TEST_NAME/$CFG.toml"
```
Comment (YuJuncen) [inline tests/lightning_fail_fast/run.sh:24]: As how @kennytm said, `! true` won't work as desired.

```suggestion
  run_lightning --backend tidb --enable-checkpoint=0 --log-file "$TEST_DIR/lightning-tidb.log" --config "tests/$TEST_NAME/$CFG.toml" && [ $? -ne 0 ]
```

File: tests/lightning_fail_fast/run.sh [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+
+  tail -n 1 $TEST_DIR/lightning-tidb.log | grep -Fq "Error 1062: Duplicate entry '1-1' for key 'uq'"
+  ! grep -Fq "restore file completed" $TEST_DIR/lightning-tidb.log
```
Comment (YuJuncen) [inline tests/lightning_fail_fast/run.sh:27]:
```suggestion
  grep -Fq "restore file completed" $TEST_DIR/lightning-tidb.log && [ $? -ne 0 ]
```

File: tests/lightning_fail_fast/run.sh [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+  ! grep -Fq "restore engine completed" $TEST_DIR/lightning-tidb.log
```
Comment (YuJuncen) [inline tests/lightning_fail_fast/run.sh:28]:
```suggestion
  grep -Fq "restore engine completed" $TEST_DIR/lightning-tidb.log && [ $? -ne 0 ]
```

**Review by ti-srebot — APPROVED** [review]
