### PR TITLE
storage: fix s3 walk directory

### LINKED ISSUE #749: Import from S3 seems to scan parent/root of given path.
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

I tried to use TiDB-Lightning to restore from an S3 bucket that holds dumpling output.

My bucket holds several different exports, each in their own subdirectory:
```
$ aws s3 ls s3://kolbe-test/
                           PRE export-2021-02-22_22:38:27/
                           PRE export-20210222-155547/
                           PRE export-20210222-165515/
2021-02-22 16:04:20        146 metadata
2021-02-22 16:04:20         66 test-schema-create.sql
2021-02-22 16:04:20        377 test.t1-schema.sql
2021-02-22 16:01:37   54044382 test.t1.sql
```

My lightning.toml file has `data-source-dir = "s3://kolbe-test/export-2021-02-22_22:38:27/?region=us-west-2`.

2. What did you expect to see?

3. What did you see instead?

It seems that for some reason the tool is reading from the root of my bucket (or at least from the parent of the path I gave), and that it then encounters .sql files that conflict with tables already read.

```
[2021/02/23 19:59:26.418 +00:00] [WARN] [config.go:490] ["currently only per-task configuration can be applied, global configuration changes can only be made on startup"] ["global config changes"="[lightning.level]"]
[2021/02/23 19:59:26.418 +00:00] [INFO] [version.go:53] ["Welcome to lightning"] ["Release Version"=v5.0.0-master] ["Git Commit Hash"=578be7fb516599dc2c6aca2bfeec73cb9c378943] ["Git Branch"=master] ["UTC Build Time"="2021-02-20 01:34:01"] ["Go Version"="go version go1.13 linux/amd64"]
[2021/02/23 19:59:26.418 +00:00] [INFO] [lightning.go:220] [cfg] [cfg="{\"id\":1614110366418978219,\"lightning\":{\"table-concurrency\":6,\"index-concurrency\":2,\"region-concurrency\":8,\"io-concurrency\":5,\"check-requirements\":true},\"tidb\":{\"host\":\"basic-tidb.tidb-cluster.svc\",\"port\":4000,\"user\":\"root\",\"status-port\":10080,\"pd-addr\":\"basic-pd.tidb-cluster.svc:2379\",\"sql-mode\":\"ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER\",\"tls\":\"false\",\"security\":{\"ca-path\":\"\",\"cert-path\":\"\",\"key-path\":\"\",\"redact-info-log\":false},\"max-allowed-packet\":67108864,\"distsql-scan-concurrency\":15,\"build-stats-concurrency\":20,\"index-serial-scan-concurrency\":20,\"checksum-table-concurrency\":2},\"checkpoint\":{\"enable\":true,\"schema\":\"tidb_lightning_checkpoint\",\"driver\":\"file\",\"keep-after-success\":false},\"mydumper\":{\"read-block-size\":65536,\"batch-size\":107374182400,\"batch-import-ratio\":0,\"data-source-dir\":\"s3://kolbe-test/export-2021-02-22_22:38:27/?region=us-west-2\\u0026force-path-style=true\",\"no-schema\":false,\"character-set\":\"auto\",\"csv\":{\"separator\":\",\",\"delimiter\":\"\\\"\",\"header\":true,\"trim-last-separator\":false,\"not-null\":false,\"null\":\"\\\\N\",\"backslash-escape\":true},\"case-sensitive\":false,\"strict-format\":false,\"max-region-size\":268435456,\"filter\":[\"*.*\",\"!mysql.*\",\"!sys.*\",\"!INFORMATION_SCHEMA.*\",\"!PERFORMANCE_SCHEMA.*\",\"!METRICS_SCHEMA.*\",\"!INSPECTION_SCHEMA.*\"],\"files\":null,\"default-file-rules\":true},\"tikv-importer\":{\"addr\":\"\",\"backend\":\"local\",\"on-duplicate\":\"replace\",\"max-kv-pairs\":4096,\"send-kv-pairs\":32768,\"region-split-size\":100663296,\"sorted-kv-dir\":\"/tmp/\",\"disk-quota\":76345581568,\"range-concurrency\":16},\"post-restore\":{\"level-1-compact\":false,\"compact\":false,\"checksum\":\"required\",\"analyze\":\"optional\",\"post-process-at-last\":true},\"cron\":{\"switch-mode\":\"5m0s\",\"log-progress\":\"5m0s\",\"check-disk-quota\":\"1m0s\"},\"routes\":null,\"security\":{\"ca-path\":\"\",\"cert-path\":\"\",\"key-path\":\"\",\"redact-info-log\":false},\"black-white-list\":{\"do-tables\":null,\"do-dbs\":null,\"ignore-tables\":null,\"ignore-dbs\":null}}"]
[2021/02/23 19:59:26.515 +00:00] [INFO] [lightning.go:282] ["load data source start"]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:298] ["[loader] file is filtered by file router"] [path=metadata]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test-schema-create.sql] [schema=test] [table=] [type=schema-schema]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1-schema.sql] [schema=test] [table=t1] [type=table-schema]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000000.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000001.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000002.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000003.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000004.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000005.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000006.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000007.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000008.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000009.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000010.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000011.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000012.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000013.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000014.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000015.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000016.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000017.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000018.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000019.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000020.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000021.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000022.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000023.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000024.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.000000025.csv] [schema=test] [table=t1] [type=csv]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:298] ["[loader] file is filtered by file router"] [path=export-20210222-155547/metadata]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=export-20210222-155547/test-schema-create.sql] [schema=test] [table=] [type=schema-schema]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=export-20210222-155547/test.t1-schema.sql] [schema=test] [table=t1] [type=table-schema]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=export-20210222-155547/test.t1.sql] [schema=test] [table=t1] [type=sql]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:298] ["[loader] file is filtered by file router"] [path=export-20210222-165515/metadata]
[2021/02/23 19:59:26.644 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=export-20210222-165515/test-schema-create.sql] [schema=test] [table=] [type=schema-schema]
[2021/02/23 19:59:26.645 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=export-20210222-165515/test.t1-schema.sql] [schema=test] [table=t1] [type=table-schema]
[2021/02/23 19:59:26.645 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=export-20210222-165515/test.t1.00001.sql] [schema=test] [table=t1] [type=sql]
[2021/02/23 19:59:26.645 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=export-20210222-165515/test.t1.00002.sql] [schema=test] [table=t1] [type=sql]
[2021/02/23 19:59:26.645 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=export-20210222-165515/test.t1.00003.sql] [schema=test] [table=t1] [type=sql]
[2021/02/23 19:59:26.645 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=export-20210222-165515/test.t1.00004.sql] [schema=test] [table=t1] [type=sql]
[2021/02/23 19:59:26.645 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=export-20210222-165515/test.t1.00005.sql] [schema=test] [table=t1] [type=sql]
[2021/02/23 19:59:26.645 +00:00] [DEBUG] [loader.go:298] ["[loader] file is filtered by file router"] [path=metadata]
[2021/02/23 19:59:26.645 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test-schema-create.sql] [schema=test] [table=] [type=schema-schema]
[2021/02/23 19:59:26.645 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1-schema.sql] [schema=test] [table=t1] [type=table-schema]
[2021/02/23 19:59:26.645 +00:00] [DEBUG] [loader.go:324] ["file route result"] [path=test.t1.sql] [schema=test] [table=t1] [type=sql]
[2021/02/23 19:59:26.645 +00:00] [ERROR] [lightning.go:285] ["load data source failed"] [takeTime=129.235513ms] [error="invalid database schema file, duplicated item - export-20210222-155547/test-schema-create.sql"]
[2021/02/23 19:59:26.645 +00:00] [ERROR] [main.go:91] ["tidb lightning encountered error stack info"] [error="invalid database schema file, duplicated item - export-20210222-155547/test-schema-create.sql"] [errorVerbose="invalid database schema file, duplicated item - export-20210222-155547/test-schema-create.sql\ngithub.com/pingcap/br/pkg/lightning/mydump.(*mdLoaderSetup).setup\n\tgithub.com/pingcap/br@/pkg/lightning/mydump/loader.go:226\ngithub.com/pingcap/br/pkg/lightning/mydump.NewMyDumpLoaderWithStore\n\tgithub.com/pingcap/br@/pkg/lightning/mydump/loader.go:158\ngithub.com/pingcap/br/pkg/lightning.(*Lightning).run\n\tgithub.com/pingcap/br@/pkg/lightning/lightning.go:284\ngithub.com/pingcap/br/pkg/lightning.(*Lightning).RunOnce\n\tgithub.com/pingcap/br@/pkg/lightning/lightning.go:193\nmain.main.func2\n\tgithub.com/pingcap/br@/cmd/tidb-lightning/main.go:86\nmain.main\n\tgithub.com/pingcap/br@/cmd/tidb-lightning/main.go:88\nruntime.main\n\truntime/proc.go:203\nruntime.goexit\n\truntime/asm_amd64.s:1357"]
[2021/02/23 19:59:26.645 +00:00] [ERROR] [main.go:92] ["tidb lightning encountered error"] [error="invalid database schema file, duplicated item - export-20210222-155547/test-schema-create.sql"]
```

4. What version of BR and TiDB/TiKV/PD are you using?

```
[2021/02/23 19:59:26.418 +00:00] [INFO] [version.go:53] ["Welcome to lightning"] ["Release Version"=v5.0.0-master] ["Git Commit Hash"=578be7fb516599dc2c6aca2bfeec73cb9c378943] ["Git Branch"=master] ["UTC Build Time"="2021-02-20 01:34:01"] ["Go Version"="go version go1.13 linux/amd64"]
```

5. Operation logs
   - Please upload `br.log` for BR if possible
   - Please upload `tidb-lightning.log` for TiDB-Lightning if possible
   - Please upload `tikv-importer.log` from TiKV-Importer if possible
   - Other interesting logs

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
close #749

### What is changed and how it works?
#713 tried to fix the s3 WalkDir prefix issue in the wrong way and introduced another bug. 

The original issue is that if prefix and subDir are both empty, the prefix parameter in the `ListObject` request then is "/", which causes s3 to return empty results.

The PR avoids adding the "/" postfix for the s3Storage object if the original prefix is an empty string.

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Release Note

 -

### CODE REVIEW

File: pkg/storage/s3.go [hunk 1]
```diff
@@ -279,8 +279,10 @@ func newS3Storage(backend *backup.S3, opts *ExternalStorageOptions) (*S3Storage,
 			return nil, errors.Annotatef(berrors.ErrStorageInvalidConfig, "Bucket %s is not accessible: %v", qs.Bucket, err)
 		}
 	}
+	if len(qs.Prefix) > 0 {
+		qs.Prefix += "/"
```
Comment (overvenus) [inline pkg/storage/s3.go:283]: What if there is a '/' already?

File: pkg/storage/s3.go [hunk 2]
```diff
@@ -378,28 +380,20 @@ func (rs *S3Storage) WalkDir(ctx context.Context, opt *WalkOption, fn func(strin
...
 	}
-
-	// NOTE: leave prefix empty if subDir is not set. Else, s3 will return empty result!
-	prefix := ""
-	if len(opt.SubDir) > 0 {
-		prefix = rs.options.Prefix + opt.SubDir
-		if len(prefix) > 0 && !strings.HasSuffix(prefix, "/") {
-			prefix += "/"
-		}
+	prefix := rs.options.Prefix + opt.SubDir
```
Comment (overvenus) [inline pkg/storage/s3.go:383]: What about `path.Join`?

File: pkg/storage/s3.go (hunk 1 above)
Comment (kennytm) [reply pkg/storage/s3.go:283]: what if we just [`path.Clean`](https://pkg.go.dev/path/#Clean) it 🤷

Comment (glorv) [reply pkg/storage/s3.go:283]: The `Prefix` is parsed from url it can't contains the "/" suffix. See: https://github.com/pingcap/br/blob/578be7fb516599dc2c6aca2bfeec73cb9c378943/pkg/storage/parse.go#L69-L70

File: pkg/storage/s3.go (hunk 2 above)
Comment (glorv) [reply pkg/storage/s3.go:383]: path.Join cannot work on windows since it separator is not "/".  And `options.Prefix` already contains the suffix "/"

File: pkg/storage/s3.go (hunk 1 above)
Comment (glorv) [reply pkg/storage/s3.go:283]: We just not want the bare "/" prefix. for other non-empty prefixes,  the suffix "/" is needed. 
BTW, maybe we shouldn't depend on the `Prefix` filed to contain the "/" suffix, but in this way, we need to change more code.

**Comment by kennytm** [comment]
```
[2021-02-24T03:59:46.545Z] TEST: [br_full_ddl] fail due to stats are not equal
```

😥

File: pkg/storage/s3_test.go [hunk 3]
```diff
@@ -881,6 +881,31 @@ func (s *s3Suite) TestWalkDir(c *C) {
 			}, nil
 		}).
 		After(secondCall)
+	forthCall := s.s3.EXPECT().
```
Comment (lichunzhu) [inline pkg/storage/s3_test.go:884]: typo?
```suggestion
	fourthCall := s.s3.EXPECT().
```

File: pkg/storage/s3_test.go [hunk 4]
```diff
@@ -881,6 +881,31 @@ func (s *s3Suite) TestWalkDir(c *C) {
...
+		ListObjectsWithContext(ctx, gomock.Any()).
+		DoAndReturn(func(_ context.Context, input *s3.ListObjectsInput) (*s3.ListObjectsOutput, error) {
+			c.Assert(aws.StringValue(input.Marker), Equals, aws.StringValue(contents[3].Key))
+			c.Assert(aws.Int64Value(input.MaxKeys), Equals, int64(4))
+			return &s3.ListObjectsOutput{
+				IsTruncated: aws.Bool(false),
+				Contents:    contents[4:],
+			}, nil
+		}).
+		After(forthCall)
```
Comment (lichunzhu) [inline pkg/storage/s3_test.go:908]:
```suggestion
		After(fourthCall)
```

**Comment by 3pointer** [comment]
> https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/4889/pipeline
> 
> ```
> [2021-02-24T03:59:46.545Z] TEST: [br_full_ddl] fail due to stats are not equal
> ```
> 
> 😥

#690 fix this test, we can merge it first

File: pkg/storage/s3.go (hunk 1 above)
Comment (lichunzhu) [reply pkg/storage/s3.go:284]: What if the user wants to load all data from one bucket?

Comment (glorv) [reply pkg/storage/s3.go:284]: The original pr is try to resolve this issue then. If the input path is the bucket name, we should leave the prefix parameter empty in the `ListObject` request, otherwise, s3 will return empty result.

**Review by lichunzhu — COMMENTED** [review]
/lgtm

File: pkg/storage/s3.go (hunk 1 above)
Comment (overvenus) [reply pkg/storage/s3.go:284]:
```go
	if len(prefix) > 0 && !strings.HasSuffix(prefix, "/") {
```

What about checking suffix too? In case the API is called from other projects.

**Review by overvenus — COMMENTED** [review]
Rest LGTM

File: pkg/storage/s3.go (hunk 1 above)
Comment (glorv) [reply pkg/storage/s3.go:284]: done

**Comment by overvenus** [comment]
LGTM

**Review by ti-srebot — APPROVED** [review]
