### PR TITLE
restore: retry scatter error

### LINKED ISSUE #1400: Scatter fails due to region "not-replicated"
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Restore v5.1.0 cluster immediately after `tiup cluster start`.

We see regions are unbalanced. 

image

2. What did you expect to see?

Regions should be scattered and balanced.

3. What did you see instead?

Unbalanced regions.

4. What version of BR and TiDB/TiKV/PD are you using?

v5.1.0

5. Operation logs

<details><summary> <b>PD log </b> </summary>

```
[2021/08/01 11:11:03.915 +09:00] [INFO] [cluster.go:604] ["region Version changed"] [region-id=4] [detail="StartKey Changed:{7480000000000000FF3300000000000000F8} -> {7480000000000000FF395F72FFFFFFFFFFFFFFFFFF0000000000FB}, EndKey:{}"] [old-version=25] [new-version=161]
[2021/08/01 11:11:03.916 +09:00] [WARN] [region_scatterer.go:255] ["region not replicated during scatter"] [region-id=63]
[2021/08/01 11:11:03.917 +09:00] [WARN] [region_scatterer.go:255] ["region not replicated during scatter"] [region-id=65]
[2021/08/01 11:11:03.917 +09:00] [WARN] [region_scatterer.go:255] ["region not replicated during scatter"] [region-id=67]
[2021/08/01 11:11:03.918 +09:00] [WARN] [region_scatterer.go:255] ["region not replicated during scatter"] [region-id=69]
[2021/08/01 11:11:03.918 +09:00] [WARN] [region_scatterer.go:255] ["region not replicated during scatter"] [region-id=71]
[2021/08/01 11:11:03.919 +09:00] [WARN] [region_scatterer.go:255] ["region not replicated during scatter"] [region-id=73]
[2021/08/01 11:11:03.916 +09:00] [INFO] [cluster_worker.go:219] ["region batch split, generate new regions"] [region-id=4] [origin="id:63 start_key:\"7480000000000000FF3300000000000000F8\" end_key:\"7480000000000000FF3700000000000000F8\" region_epoch:<conf_ver:1 version:>
[2021/08/01 11:11:03.919 +09:00] [WARN] [region_scatterer.go:255] ["region not replicated during scatter"] [region-id=75]
[2021/08/01 11:11:03.920 +09:00] [WARN] [region_scatterer.go:255] ["region not replicated during scatter"] [region-id=77]
[2021/08/01 11:11:03.920 +09:00] [WARN] [region_scatterer.go:255] ["region not replicated during scatter"] [region-id=79]
[2021/08/01 11:11:03.921 +09:00] [WARN] [region_scatterer.go:255] ["region not replicated during scatter"] [region-id=81]
[2021/08/01 11:11:03.921 +09:00] [WARN] [region_scatterer.go:255] ["region not replicated during scatter"] [region-id=83]
[2021/08/01 11:11:03.922 +09:00] [WARN] [region_scatterer.go:255] ["region not replicated during scatter"] [region-id=85]
[2021/08/01 11:11:03.922 +09:00] [WARN] [region_scatterer.go:255] ["region not replicated during scatter"] [region-id=87]
```

</details>

### PR DESCRIPTION
**Pull request by YuJuncen**
### What problem does this PR solve? 
fix #1400 

### What is changed and how it works?
Add a retry on scatter failure, instead of giving up scattering the region directly.

### Check List 

Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)

In a workload with little huge tables, many retries were captured.

image

### Release note

 - Fix a bug that caused regions spread unbalanced after the restoration.

### CODE REVIEW

File: pkg/restore/split_client.go [hunk 1]
```diff
@@ -498,3 +500,52 @@ func checkRegionEpoch(new, old *RegionInfo) bool {
...
+}
+
+func (b *scatterBackoffer) giveUp() time.Duration {
+	b.attempt = 0
+	return 0
+}
+
+// NextBackoff returns a duration to wait before retrying again
+func (b *scatterBackoffer) NextBackoff(err error) time.Duration {
+	// There are 3 type of reason that BR would reject a `scatter` request:
```
Comment (YuJuncen) [inline pkg/restore/split_client.go:526]:
```suggestion
	// There are 3 type of reason that PD would reject a `scatter` request:
```

**Review by zwj-coder — APPROVED** [review]

**Review by 3pointer — APPROVED** [review]
